export const pointCloudOptions = [
  // "Zaghetto.pcd",
  // "brisk_descriptors_gt.pcd",
  // "brisk_image_gt.pcd",
  // "brisk_keypoints_gt.pcd",
  // "bun0.pcd",
  // "bun01.pcd",
  // "bun02.pcd",
  // "bun03.pcd",
  // "bun4.pcd",
  // "bunny.pcd",
  // "car6.pcd",
  // "colored_cloud.pcd",
  // "cturtle.pcd",
  // "curve2d.pcd",
  // "curve3d.pcd",
  // "curve_close.pcd",
  // "five_people.pcd",
  // "ism_test.pcd",
  // "lamppost.pcd",
  // "milk.pcd",
  // "milk_cartoon_all_small_clorox.pcd",
  // "milk_color.pcd",
  // "nhood_test.pcd",
  // "noisy_slice_displaced.pcd",
  // "octants.pcd",
  // "office1.pcd",
  // "office1_keypoints.pcd",
  // "office2_keypoints.pcd",
  // "pcl_logo.pcd",
  // "rops_cloud.pcd",
  // "sac_plane_test.pcd",
  // "stereo_left.pcd",
  // "stereo_right.pcd",
  // "table_scene_mug_stereo_textured.pcd",
  "home.pcd",
  "home2.pcd",
  "am_office1.pcd",
  "am_office3.pcd",
];